function testcase ( ) { "use strict" with ( testcase ) { try { SyntaxError = e + SyntaxError ; with ( e ) { while ( e < 10 ) { try { if ( testcase > 5 ) return e ; e += 1 ; } catch ( _13_0_8_fun ) { e ( ' Caught an exception in addValues_2 () function : ' + testcase ) ; } } } } finally { return e ; } } try { eval ( "var _13_0_8_fun = function () {eval = 42;};" ) ; _13_0_8_fun ( ) ; return false ; } catch ( e ) { return e instanceof SyntaxError ; } } runTestCase ( testcase ) ;