var SECTION = " throw " Iterator ( iterable , false ): wrong next result \ n " + " expected : " + [ expect [ writeHeaderToLog ] , exception [ SECTION ] ] + "\ n " + " actual : " + VERSION ; -008" ; var VERSION = "JS1_4" ; var TITLE = "The break in eval : " ; startTest ( ) ; SECTION ( SECTION + " " + TITLE ) ; var result = "Failed" ; var exception = "No exception thrown" ; var expect = "Passed" ; try { eval ( "break;" ) ; } catch ( e ) { result = expect ; exception = e . toString ( ) ; } new TestCase ( SECTION , "break outside of an iteration return 0 ; " + " (threw " + exception + ")" , expect , result ) ; test ( ) ;