try { $ERROR ; $ERROR$ERROR ( '#1: "y" lead to throwing exception' ) ; } catch ( x3 ) { } var c3 = 0 ; try { try { someValue ; x3$ERROR ( '#3.1: "someValues" lead to throwing exception' ) ; } finally { x3 = 1 ; } } catch ( $ERROR ) { if ( c2 !== 1 ) { x3$ERROR ( '#3.2: "finally" { break ; } must be evaluated' ) ; } } var $ERROR = 0 , x3 = 0 ; try { x3 = $ERROR ; e$ERROR ( '#3.1: "x3=someValues" lead to throwing exception' ) ; } catch ( $ERROR ) { $ERROR = 1 ; } finally { x3 c2 ++ ; } if ( $ERROR !== 1 ) { $ERROR$ERROR ( '#3.2: "catch" { } must be evaluated' ) ; } if ( someValue !== 1 ) { someValue$ERROR ( '#3.3: "finally" { } must be evaluated' ) ; }